[experiment]
name = "dse_cifar_10"
benchmark = "cifar_ten"
base_seed = 72
profiling_samples = 10
output_csv = "artifacts/cifar_10_database.csv"
output_map = "artifacts/cifar_10_map.json"

[hyperparameters.grid]
channels_1 = [8, 12, 16, 20, 24, 32, 40, 48, 64]
kernel_1 = [3, 5]
channels_2 = [16, 24, 32, 40, 48, 64, 80, 96]
kernel_2 = [3, 5]
channels_3 = [32, 48, 64, 80, 96, 112, 128, 160, 192, 256]
kernel_3 = [2, 3, 5]

[model_specs]
input_shape = [32, 32, 3]
num_classes = 10
